#!/usr/bin/env sh

# https://github.com/c00kiemon5ter/iii/blob/master/connect.sh

: "${ircdir:=$HOME/irc}"
: "${nick:=aetherion}"

# server info functions
libera() {
    server='irc.libera.chat'
    channels="#vim #emacs #neovim ##rust ##india #gnulinuxindia #gnulinuxindia-offtopic #linux #suckless ##programming #c"
}

# these match the functions above
networks="libera"

for network in $networks; do
    unset server channels port
    "$network" # set the appropriate vars

    while true; do
        # cleanup
        rm -f "$ircdir/$server/in"
        # connect to network -- password is set through the env var synonym to the network name
        ii -i "$ircdir" -n "$nick" -k "$network" -s "$server" -p "${port:-6667}" &
        pid="$!"

        # wait for the connection
        while ! test -p "$ircdir/$server/in"; do sleep .3; done

        # auth to services either using plain password stored in ident file
        # or using pass
        if [ -e "$ircdir/$server/ident" ]
            then printf "/j nickserv identify %s\n" "$(cat "$ircdir/$server/ident")" > "$ircdir/$server/in"
        else
            printf "/j nickserv identify %s\n" "$(pass libera)" > "$ircdir/$server/in"
        fi && rm -f "$ircdir/$server/nickserv/out" # clean that up - ident passwd is in there

        # join channels
        printf "/j %s\n" $channels > "$ircdir/$server/in"

        # if connection is lost reconnect
        wait "$pid"
    done &
done
